## Numpy
NumPy (Numerical Python) is a fundamental package for scientific computing in Python.
It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently.

In [276]:
import numpy as np

# 1 dimensional array:
arr1 = np.array([27, 84, 31, 40, 75, 83, 12])

# 2 dimensional array:
arr2 = np.array([
    [6, 3, 9],
    [9, 1, 2],
    [2, 8, 4]
])

### Numpy Operations
You can perform several operations with numpy

In [277]:
# Basic arithmetics
print(arr1 + 10) # Add 10 to every element
print(arr1 - 5) # Subtracts 5 to every element
print(arr1 * 2) # Multiply every element by 2
print(arr1 / 10) # Divide every element by 10

[37 94 41 50 85 93 22]
[22 79 26 35 70 78  7]
[ 54 168  62  80 150 166  24]
[2.7 8.4 3.1 4.  7.5 8.3 1.2]
